ARG GOLANG_VERSION="1.19.2"

FROM golang:$GOLANG_VERSION-alpine as builder
RUN apk --no-cache add git
RUN git clone https://codeberg.org/peterzam/socks5
WORKDIR /go/socks5/cmd/server
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-s' -o ./server

FROM scratch
COPY --from=builder /go/socks5/cmd/server/server /server
ENTRYPOINT ["/server"]